/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.practica1estructura.frame;

import com.mycompany.practica1estructura.HiloAnimacion;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Mariano
 */
public class AnimacionCaballo extends javax.swing.JFrame {
    /**
     * Creates new form AnimacionVuelo
     */
    FondoInicio fondoVuelo = new FondoInicio();//Creamos un nuevo fondo
    //estructuramos una manera estatica para poder cerrarla y abrirla desde cualquier lado
    public static AnimacionCaballo frameAnimacionCaballo;
    public static void iniciarCarrera(){
        frameAnimacionCaballo=new AnimacionCaballo();
    }
    public static void visible(){
        frameAnimacionCaballo.setVisible(true);
    }
    public AnimacionCaballo() {
        this.setContentPane(fondoVuelo);//Realizamos la pintada de nuestro fondo
        initComponents();
        movientoHilo();//llamamos a movientoHilo
        this.setLocationRelativeTo(null);//Centramos nuestro frame
    }
    public void movientoHilo(){
        HiloAnimacion h = new HiloAnimacion();//creamos un hilo animacion
        h.start();//iniciamos hilo animacion
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        destino = new javax.swing.JLabel();
        origen2 = new javax.swing.JLabel();
        volando = new javax.swing.JLabel();
        origen3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Animacion Carrera");

        jPanel2.setOpaque(false);

        destino.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        destino.setForeground(new java.awt.Color(0, 0, 0));
        destino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/meta.png"))); // NOI18N

        origen2.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        origen2.setForeground(new java.awt.Color(0, 0, 0));
        origen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inicio.png"))); // NOI18N

        volando.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        volando.setForeground(new java.awt.Color(0, 0, 0));
        volando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carreraCurso.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(origen2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(destino)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 294, Short.MAX_VALUE)
                        .addComponent(volando)
                        .addGap(426, 426, 426))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(422, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(destino)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(volando)
                        .addGap(23, 23, 23)
                        .addComponent(origen2)))
                .addGap(43, 43, 43))
        );

        origen3.setFont(new java.awt.Font("Engravers MT", 1, 36)); // NOI18N
        origen3.setForeground(new java.awt.Color(0, 0, 0));
        origen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/metaIcono.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(822, Short.MAX_VALUE)
                .addComponent(origen3)
                .addGap(65, 65, 65))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addComponent(origen3)
                .addGap(67, 67, 67))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    class FondoInicio extends JPanel{//creamos una clase parametrica o generica extendiendo de JPanel
        private Image imagen;//establecemos que sea tipo imagen
        @Override//sobrescribimos la clase JPanel especificamente el metodo paint
        public void paint(Graphics g){ 
            imagen = new ImageIcon(getClass().getResource("/images/FondoCaballo.jpg")).getImage();//igualamos nuestra variable al fondo que queremos
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);//damos las dimensiones
            setOpaque(false);//Ponemos que el panel no sea visible
            super.paint(g);//llamos a la clase super para que cumpla con las funcionalidades del JPanel
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel destino;
    public static javax.swing.JPanel jPanel2;
    private javax.swing.JLabel origen2;
    private javax.swing.JLabel origen3;
    private javax.swing.JLabel volando;
    // End of variables declaration//GEN-END:variables
}
