/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.practica1estructura.frame;

import static com.mycompany.practica1estructura.frame.Inicio.apostadores;
import static com.mycompany.practica1estructura.frame.Inicio.ordenarAlfabeticamente;
import static com.mycompany.practica1estructura.frame.Inicio.ordenarPunteo;
import com.mycompany.practica1estructura.objeto.LlenarResultados;
import com.mycompany.practica1estructura.objeto.OrdenCarrera;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Mariano
 */

public class VerResultados extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarOrdenApuesta
     */
    public static OrdenCarrera[] ordenDeCarrera=new OrdenCarrera[1];

    FondoInicio seleccionApuesta = new FondoInicio();//Creamos un nuevo fondo
    public VerResultados() {
        
        this.setContentPane(seleccionApuesta);//Realizamos la pintada de nuestro fondo
        initComponents();
        this.setLocationRelativeTo(null);//Centramos nuestro frame
        LlenarResultados.completarTablaResultados(apostadores, resultadosTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ordenarNombre = new javax.swing.JButton();
        ordenarPunteo = new javax.swing.JButton();
        regresarPunteo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultadosTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setOpaque(false);

        ordenarNombre.setBackground(new java.awt.Color(51, 255, 204));
        ordenarNombre.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        ordenarNombre.setForeground(new java.awt.Color(0, 0, 0));
        ordenarNombre.setText("Ordenar por nombre");
        ordenarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarNombreActionPerformed(evt);
            }
        });

        ordenarPunteo.setBackground(new java.awt.Color(51, 255, 204));
        ordenarPunteo.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        ordenarPunteo.setForeground(new java.awt.Color(0, 0, 0));
        ordenarPunteo.setText("Ordenar Por punteo");
        ordenarPunteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarPunteoActionPerformed(evt);
            }
        });

        regresarPunteo.setBackground(new java.awt.Color(255, 0, 0));
        regresarPunteo.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        regresarPunteo.setForeground(new java.awt.Color(0, 0, 0));
        regresarPunteo.setText("Regresar");
        regresarPunteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarPunteoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/textResultados.png"))); // NOI18N

        resultadosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NOMBRE DE APOSTADOR", "MONTO", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "PUNTEO"
            }
        ));
        jScrollPane3.setViewportView(resultadosTable);

        jLabel8.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/datoResultado.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(ordenarPunteo)
                                .addGap(136, 136, 136)
                                .addComponent(ordenarNombre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(regresarPunteo)
                                .addGap(112, 112, 112)
                                .addComponent(jLabel7)))
                        .addGap(74, 74, 74)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regresarPunteo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ordenarPunteo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ordenarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ordenarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarNombreActionPerformed
        ordenarAlfabeticamente();
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerResultados().setVisible(true);
            }
        });
    }//GEN-LAST:event_ordenarNombreActionPerformed

    private void ordenarPunteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarPunteoActionPerformed
        ordenarPunteo();
        this.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerResultados().setVisible(true);
            }
        });
    }//GEN-LAST:event_ordenarPunteoActionPerformed

    private void regresarPunteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarPunteoActionPerformed
        this.dispose();
    }//GEN-LAST:event_regresarPunteoActionPerformed

    /**
     * @param args the command line arguments
     */
    class FondoInicio extends JPanel{//creamos una clase parametrica o generica extendiendo de JPanel
        private Image imagen;//establecemos que sea tipo imagen
        @Override//sobrescribimos la clase JPanel especificamente el metodo paint
        public void paint(Graphics g){ 
            imagen = new ImageIcon(getClass().getResource("/images/Resultados.png")).getImage();//igualamos nuestra variable al fondo que queremos
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);//damos las dimensiones
            setOpaque(false);//Ponemos que el panel no sea visible
            super.paint(g);//llamos a la clase super para que cumpla con las funcionalidades del JPanel
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton ordenarNombre;
    private javax.swing.JButton ordenarPunteo;
    private javax.swing.JButton regresarPunteo;
    public static javax.swing.JTable resultadosTable;
    // End of variables declaration//GEN-END:variables
}
